FROM python:3.7-alpine

WORKDIR /app

# We copy just the requirements.txt first to leverage Docker cache
COPY ./server_requirements.txt /app/server_requirements.txt

RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev openssl-dev libressl-dev libffi-dev
RUN pip install -r server_requirements.txt

WORKDIR /app

COPY . /app

ENTRYPOINT [ "python" ]

CMD [ "server.py" ]
